PROJECT = "Linkedin-Scalable-invitations"
DEFAULT_OS = "Windows"
PTH_FILE_NAME = "LinkedinScalableProject.pth"
WINDOWS_PTH_FILE_PATH = "{}\\AppData\\Local\\Programs\\Python\\Python{}{}\\Lib\\site-packages\\{}"
LINUX_PATH_FILE_PATH = "/usr/local/lib/python{}.{}/site-packages/{}"
LINUX_SPLIT_PARAM = "/"
WINDOWS_SPLIT_PARAM = "\\"
